[flake8]
max-line-length = 120
ignore = D100

[tox]
skipsdist = True

[testenv]
basepython = python3
setenv =
    PYTHONPATH={toxinidir}/src

[testenv:unit]
deps =
    pyyaml
    pytest
    pytest-cov
    requests
    git+https://github.com/juju-solutions/charms.unit_test/#egg=charms.unit_test
commands =
    pytest \
      --cov-report term-missing \
      --cov reactive.kata --cov-fail-under 30 \
      --tb native -s {posargs}

[testenv:lint]
deps =
    flake8
    flake8-docstrings
    black
commands =
   flake8 {toxinidir}/src {toxinidir}/tests
   black --check {toxinidir}/src {toxinidir}/tests

[testenv:format]
envdir = {toxworkdir}/lint
deps =
   black
commands = black {toxinidir}/src {toxinidir}/tests

[testenv:validate-wheelhouse]
deps =
    git+https://github.com/juju/charm-tools.git
    path<17
allowlist_externals = {toxinidir}/tests/validate-wheelhouse.sh
commands = {toxinidir}/tests/validate-wheelhouse.sh
